### PR TITLE
Fix gatsby-image graphql query

### PR DESCRIPTION
**Pull request by rizumu**
@abflussengel this fixes the GraphQL query

### CODE REVIEW

**Review by hannarosenfeld — APPROVED** [review]

**Comment by abflussengel** [comment]
Fix GraphQL query for Gatbsy Img

**Comment by abflussengel** [comment]
uhm

**Comment by hannarosenfeld** [comment]
Fix gatsby-image graphql query.

**Comment by hannarosenfeld** [comment]
Fix gatsby-image graphql query

**Pull request closed without merging**
